### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by jjliyu** [videgro/Ships#4] opened 2020-06-14 08:33 UTC
thank you ,Great job, but compilation is always unsuccessful. It is lack of C file and cannot generate  .so native  library file.  please share .so file

**Comment by videgro** [comment] 2020-06-26 07:52
Duplicate of #3 It is not possible to build a working product from this GIT repo (as intended). You can find a compiled version at Google Play store: https://play.google.com/store/apps/details?id=net.videgro.ships

**Closed as completed by videgro** 2020-06-26 07:52 UTC
